apiVersion: v1
kind: Pod
metadata:
 name: webapp
 labels: 
  appLabel: webapp
  release: "0"
spec:
 containers:
 - name: webapp
   image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---

apiVersion: v1
kind: Pod
metadata:
 name: webapp-release-0-5
 labels:
  appLabel: webapp
  release: "0-5"
spec:
 containers:
 - name: webapp
   image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
 name: activemq
 labels:
  appLabel: queue
spec:
 containers:
 - name: activemq
   image: richardchesterwood/k8s-fleetman-queue:release1

