apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: webapp
spec:
 replicas: 1
 selector:
  matchLabels:
   appLabel: webapp
 template:
  metadata:
   labels:
    appLabel: webapp 
  spec:
   containers:
   - name: webapp
     image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
 name: activemq
 labels:
  appLabel: queue
spec:
 containers:
 - name: activemq
   image: richardchesterwood/k8s-fleetman-queue:release1

